name: noise_meter
description: A Flutter plugin for collecting noise from the phone's microphone.
publish_to: 'none'

version: 3.0.3
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/noise_meter


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # audio_streamer: ^2.0.3
  audio_streamer:
    git:
      url: https://github.com/Color-Lights/flutter-plugins_streamer_noisemeter.git
      path: packages/audio_streamer


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
